// Lista de países (nome em português + código ISO 3166-1 alpha-2) em ordem alfabética.
// Inclui os 193 estados-membros da ONU + Vaticano e Palestina (observadores comumente usados em simulações).
export const COUNTRIES = [
  ['Afeganistão', 'AF'],
  ['África do Sul', 'ZA'],
  ['Albânia', 'AL'],
  ['Alemanha', 'DE'],
  ['Andorra', 'AD'],
  ['Angola', 'AO'],
  ['Antígua e Barbuda', 'AG'],
  ['Arábia Saudita', 'SA'],
  ['Argélia', 'DZ'],
  ['Argentina', 'AR'],
  ['Armênia', 'AM'],
  ['Austrália', 'AU'],
  ['Áustria', 'AT'],
  ['Azerbaijão', 'AZ'],
  ['Bahamas', 'BS'],
  ['Bahrein', 'BH'],
  ['Bangladesh', 'BD'],
  ['Barbados', 'BB'],
  ['Bélgica', 'BE'],
  ['Belize', 'BZ'],
  ['Benin', 'BJ'],
  ['Bielorrússia', 'BY'],
  ['Bolívia', 'BO'],
  ['Bósnia e Herzegovina', 'BA'],
  ['Botsuana', 'BW'],
  ['Brasil', 'BR'],
  ['Brunei', 'BN'],
  ['Bulgária', 'BG'],
  ['Burkina Faso', 'BF'],
  ['Burundi', 'BI'],
  ['Butão', 'BT'],
  ['Cabo Verde', 'CV'],
  ['Camarões', 'CM'],
  ['Camboja', 'KH'],
  ['Canadá', 'CA'],
  ['Catar', 'QA'],
  ['Cazaquistão', 'KZ'],
  ['Chade', 'TD'],
  ['Chile', 'CL'],
  ['China', 'CN'],
  ['Chipre', 'CY'],
  ['Colômbia', 'CO'],
  ['Comores', 'KM'],
  ['Congo', 'CG'],
  ['Coreia do Norte', 'KP'],
  ['Coreia do Sul', 'KR'],
  ['Costa do Marfim', 'CI'],
  ['Costa Rica', 'CR'],
  ['Croácia', 'HR'],
  ['Cuba', 'CU'],
  ['Dinamarca', 'DK'],
  ['Djibuti', 'DJ'],
  ['Dominica', 'DM'],
  ['Egito', 'EG'],
  ['El Salvador', 'SV'],
  ['Emirados Árabes Unidos', 'AE'],
  ['Equador', 'EC'],
  ['Eritreia', 'ER'],
  ['Eslováquia', 'SK'],
  ['Eslovênia', 'SI'],
  ['Espanha', 'ES'],
  ['Essuatíni', 'SZ'],
  ['Estados Unidos', 'US'],
  ['Estônia', 'EE'],
  ['Etiópia', 'ET'],
  ['Fiji', 'FJ'],
  ['Filipinas', 'PH'],
  ['Finlândia', 'FI'],
  ['França', 'FR'],
  ['Gabão', 'GA'],
  ['Gâmbia', 'GM'],
  ['Gana', 'GH'],
  ['Geórgia', 'GE'],
  ['Granada', 'GD'],
  ['Grécia', 'GR'],
  ['Guatemala', 'GT'],
  ['Guiana', 'GY'],
  ['Guiné', 'GN'],
  ['Guiné-Bissau', 'GW'],
  ['Guiné Equatorial', 'GQ'],
  ['Haiti', 'HT'],
  ['Honduras', 'HN'],
  ['Hungria', 'HU'],
  ['Iêmen', 'YE'],
  ['Ilhas Marshall', 'MH'],
  ['Ilhas Salomão', 'SB'],
  ['Índia', 'IN'],
  ['Indonésia', 'ID'],
  ['Irã', 'IR'],
  ['Iraque', 'IQ'],
  ['Irlanda', 'IE'],
  ['Islândia', 'IS'],
  ['Israel', 'IL'],
  ['Itália', 'IT'],
  ['Jamaica', 'JM'],
  ['Japão', 'JP'],
  ['Jordânia', 'JO'],
  ['Kuwait', 'KW'],
  ['Laos', 'LA'],
  ['Lesoto', 'LS'],
  ['Letônia', 'LV'],
  ['Líbano', 'LB'],
  ['Libéria', 'LR'],
  ['Líbia', 'LY'],
  ['Liechtenstein', 'LI'],
  ['Lituânia', 'LT'],
  ['Luxemburgo', 'LU'],
  ['Macedônia do Norte', 'MK'],
  ['Madagascar', 'MG'],
  ['Malásia', 'MY'],
  ['Malawi', 'MW'],
  ['Maldivas', 'MV'],
  ['Mali', 'ML'],
  ['Malta', 'MT'],
  ['Marrocos', 'MA'],
  ['Maurícia', 'MU'],
  ['Mauritânia', 'MR'],
  ['México', 'MX'],
  ['Mianmar', 'MM'],
  ['Micronésia', 'FM'],
  ['Moçambique', 'MZ'],
  ['Moldávia', 'MD'],
  ['Mônaco', 'MC'],
  ['Mongólia', 'MN'],
  ['Montenegro', 'ME'],
  ['Namíbia', 'NA'],
  ['Nauru', 'NR'],
  ['Nepal', 'NP'],
  ['Nicarágua', 'NI'],
  ['Níger', 'NE'],
  ['Nigéria', 'NG'],
  ['Noruega', 'NO'],
  ['Nova Zelândia', 'NZ'],
  ['Omã', 'OM'],
  ['Países Baixos', 'NL'],
  ['Palau', 'PW'],
  ['Palestina', 'PS'],
  ['Panamá', 'PA'],
  ['Papua-Nova Guiné', 'PG'],
  ['Paquistão', 'PK'],
  ['Paraguai', 'PY'],
  ['Peru', 'PE'],
  ['Polônia', 'PL'],
  ['Portugal', 'PT'],
  ['Quênia', 'KE'],
  ['Quirguistão', 'KG'],
  ['Reino Unido', 'GB'],
  ['República Centro-Africana', 'CF'],
  ['República Democrática do Congo', 'CD'],
  ['República Dominicana', 'DO'],
  ['República Tcheca', 'CZ'],
  ['Romênia', 'RO'],
  ['Ruanda', 'RW'],
  ['Rússia', 'RU'],
  ['Samoa', 'WS'],
  ['San Marino', 'SM'],
  ['Santa Lúcia', 'LC'],
  ['São Cristóvão e Névis', 'KN'],
  ['São Tomé e Príncipe', 'ST'],
  ['São Vicente e Granadinas', 'VC'],
  ['Seicheles', 'SC'],
  ['Senegal', 'SN'],
  ['Serra Leoa', 'SL'],
  ['Sérvia', 'RS'],
  ['Síria', 'SY'],
  ['Somália', 'SO'],
  ['Sri Lanka', 'LK'],
  ['Sudão', 'SD'],
  ['Sudão do Sul', 'SS'],
  ['Suécia', 'SE'],
  ['Suíça', 'CH'],
  ['Suriname', 'SR'],
  ['Tailândia', 'TH'],
  ['Tajiquistão', 'TJ'],
  ['Tanzânia', 'TZ'],
  ['Timor-Leste', 'TL'],
  ['Togo', 'TG'],
  ['Tonga', 'TO'],
  ['Trinidad e Tobago', 'TT'],
  ['Tunísia', 'TN'],
  ['Turcomenistão', 'TM'],
  ['Turquia', 'TR'],
  ['Tuvalu', 'TV'],
  ['Ucrânia', 'UA'],
  ['Uganda', 'UG'],
  ['Uruguai', 'UY'],
  ['Uzbequistão', 'UZ'],
  ['Vanuatu', 'VU'],
  ['Vaticano', 'VA'],
  ['Venezuela', 'VE'],
  ['Vietnã', 'VN'],
  ['Zâmbia', 'ZM'],
  ['Zimbábue', 'ZW']
]

export function flagEmoji(iso2) {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}
